# Build env
FROM node:15.6.0-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json .

# Installing packages
RUN yarn install --frozen-lockfile --silent

# build
COPY . .
RUN yarn run build

# Production env
FROM nginx:1.19.6-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
